name: Deploy to EC2 via SSM

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Deploy to EC2
      run: |
        COMMAND_ID=$(aws ssm send-command \
          --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=[
            "set -e",
            "echo Starting deployment",
            "cd ~/MovieSwiper-backend",
            "echo Pulling latest code",
            "git pull origin master",
            "echo Installing depencies",
            "npm install",
            "echo Building application",
            "npm run build",
            "echo Restarting application",
            "pkill -f \"node\" || true",
            "nohup npm start > app.log 2>&1 &",
            "echo Deployment complete!"
          ]' \
          --output text \
          --query "Command.CommandId")
        
        echo "Command ID: $COMMAND_ID"
        
        aws ssm wait command-executed \
          --command-id "$COMMAND_ID" \
          --instance-id "${{ secrets.EC2_INSTANCE_ID }}"
        
        aws ssm get-command-invocation \
          --command-id "$COMMAND_ID" \
          --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
          --query "StandardOutputContent" \
          --output text

          - name: Get command output on failure
            if: always()
            run: |
              echo "=== STDOUT ==="
              aws ssm get-command-invocation \
                --command-id "6b437fbd-e48e-4937-8b78-c44e121c8c99" \
                --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
                --query "StandardOutputContent" \
                --output text
              
              echo "=== STDERR ==="
              aws ssm get-command-invocation \
                --command-id "6b437fbd-e48e-4937-8b78-c44e121c8c99" \
                --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
                --query "StandardErrorContent" \
                --output text
